# -*- coding: utf-8 -*-
"""PLOTLY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yD1XjkBUIrApn6GJbTs0sD-UTiVfdo-a
"""

# QUESTION.1 Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
# scatter plot for age and fare columns in the titanic dataset.
# ANSWER
import seaborn as sns
import plotly.express as px

# Load the Titanic dataset from Seaborn
titanic = sns.load_dataset("titanic")

# Create a scatter plot using Plotly Express
fig = px.scatter(titanic, x="age", y="fare", title="Scatter Plot of Age vs Fare in Titanic Dataset")

# Show the plot
fig.show()

"""# New Section

# New Section
"""

# QUESTION.2 Using the tips dataset in the Plotly library, plot a box plot using Plotly express.
# ANSWER
import seaborn as sns
import plotly.express as px

# Load the tips dataset from seaborn
tips = sns.load_dataset("tips")

# Create a box plot using Plotly Express
fig = px.box(tips, x="day", y="total_bill", title="Box Plot of Total Bill Amount by Day")

# Show the plot
fig.show()

# QUESTION.3 Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in the tips dataset. Also, use the
#            "smoker" column with the pattern_shape parameter and the "day" column with the color parameter.
# ANSWER
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

# Load the tips dataset
tips = sns.load_dataset("tips")

# Create a histogram with Plotly Express
fig = px.histogram(
    tips,
    x="sex",
    y="total_bill",
    color="day",
    pattern_shape="smoker",
    title="Histogram of Total Bill by Sex",
    labels={"total_bill": "Total Bill"},
)

# Update layout for better visualization
fig.update_layout(
    xaxis_title="Sex",
    yaxis_title="Frequency",
    legend_title="Day",
    legend_traceorder="reversed",
)

# Show the plot
fig.show()

# QUSTION.4 Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for the color parameter.
# Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
# dimensions parameter.
# ANSWER
import plotly.express as px
import pandas as pd

# Load the Iris dataset
df = px.data.iris()

# Create the scatter matrix plot
fig = px.scatter_matrix(
    df,
    dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],
    color="species",
    title="Scatter Matrix Plot of Iris Dataset by Species",
    labels={"species": "Species"},
)

# Customize the appearance of the plot
fig.update_traces(diagonal_visible=False)  # Hide histograms on the diagonal
fig.update_layout(width=800, height=800)

# Show the plot
fig.show()

# QUESTION.5 What is Distplot? Using Plotly express, plot a distplot.
# ANSWER
import plotly.express as px

# Sample data (replace this with your own dataset)
data = [1, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 8, 9]

# Create a distribution plot using px.histogram
fig = px.histogram(data,  nbins=5, title="Distribution Plot")

# Customize the layout (optional)
fig.update_layout(
    xaxis_title="Value",
    yaxis_title="Frequency",
    bargap=0.05,  # Gap between bars
)

# Show the plot
fig.show()

